#Dictionary of Traits and their activation thresholds
activation_thresholds = {
  "Arcana": 2,
  "Chrono": 2,
  "Dragon": 2,
  "Eldritch": 3,
  "Faerie": 2,
  "Frost": 3,
  "Honeymancy": 3,
  "Portal": 3,
  "Pyro": 2,
  "Sugarcraft": 2,
  "Witchcraft": 2,
  "Bastion": 2,
  "Blaster": 2,
  "Hunter": 2,
  "Incantor": 2,
  "Mage": 3,
  "Multistriker": 3,
  "Preserver": 2,
  "Scholar": 2,
  "Shapeshifter": 2,
  "Vanguard": 2,
  "Warrior": 2
}